//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bstrap2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_view1
    {
        public int user { get; set; }
        public int viewN { get; set; }
        public string head { get; set; }
        public string body { get; set; }
        public string foot { get; set; }
    }
}
